apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  selector:
    matchLabels:
      name: mongodb
  serviceName: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        name: mongodb
    spec:
      containers:
        - name: mongodb
          image: docker.io/bitnami/mongodb:6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 21017
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MONGODB_ROOT_PASSWORD
              value: root
            - name: MONGODB_USERNAME
              value: mongodb
            - name: MONGODB_PASSWORD
              value: mongodb
            - name: MONGODB_DATABASE
              value: mongodb
            - name: MONGODB_ADVERTISE_IP
              value: "true"
            - name: MONGODB_DEFAULT_ENABLE_DIRECTORY_PER_DB
              value: "true"
            - name: MONGODB_ADVERTISED_PORT_NUMBER
              value: "30017"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  selector:
    name: mongodb
  externalIPs:
    - 192.168.1.100
  ports:
    - port: 21017
      targetPort: 21017
      nodePort: 30017
      name: main
  type: LoadBalancer