server:
  port: 8080
  servlet:
    context-path: /
spring:
  data:
    mongodb:
      uri: mongodb+srv://m001-student:6cyw680Zu5qT50aX@sandbox.j55egoq.mongodb.net/?retryWrites=true&w=majority
      database: mongodb

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
